kind: Service
apiVersion: v1
metadata:
  name: basic
spec:
  type: NodePort
  selector:
    app: basic
  ports:
  - port: 8080
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic
  labels:
    app: basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic
  template:
    metadata:
      name: basic
      labels:
        app: basic
    spec:
      containers:
      - name: basic
        image: docker.io/library/basic:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /etc/config
            name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: basic
